tasks:
  - init: |
      rustup default nightly
      rustup +nightly component add rustfmt
      cargo build
    command: |
      cargo run

vscode:
  extensions:
    - matklad.rust-analyzer
    - serayuzgur.crates
    - bungcip.better-toml
